[theme]
primaryColor = "#E74C3C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false